export const exportFields = [
  {
    title: '选择字段',
    prop: 'fields',
    data: [
      {
        label: '系统所属部门',
        value: 'sysDeptName',
      }, {
        label: '信息系统名称',
        value: 'sysDsgt',
      }, {
        label: '系统功能、服务简介',
        value: 'sysFctn',
      }, {
        label: '项目立项审批部门',
        value: 'apvlDept',
      }, {
        label: '项目立项审批日期',
        value: 'apvlDate',
      }, {
        label: '预算项目名称',
        value: 'bdgtDsgt',
      }, {
        label: '预算涉及的年度起',
        value: 'bdgtStrt',
      }, {
        label: '预算涉及的年度止',
        value: 'bdgtDeadline',
      }, {
        label: '是否为僵尸系统',
        value: 'uselessSys',
      }, {
        label: '系统开始使用日期',
        value: 'sysStart',
      }, {
        label: '系统停止使用日期',
        value: 'sysExpr',
      }, {
        label: '系统状态',
        value: 'sysState',
      }, {
        label: '建设资金来源',
        value: 'fundsSources',
      }, {
        label: '归口业务处室',
        value: 'servOfc',
      }, {
        label: '处室联系人',
        value: 'cntct',
      }, {
        label: '处室联系方式',
        value: 'cntctInfo',
      }, {
        label: '系统部署情况',
        value: 'sysDeploy',
      }, {
        label: '网络环境',
        value: 'ntwk',
      }, {
        label: '使用范围-区域',
        value: 'useRange',
      }, {
        label: '使用范围-用户',
        value: 'useUser',
      }, {
        label: '系统使用频率（上年度累计访问数）',
        value: 'sysUsed',
      }, {
        label: '使用频率测算依据',
        value: 'usedBasis',
      }, {
        label: '数据产生方式',
        value: 'dataGen',
      }, {
        label: '数据更新频率',
        value: 'dataUpd',
      }, {
        label: '数据库格式',
        value: 'dbType',
      }, {
        label: '数据规模（G）',
        value: 'dataSize',
      }, {
        label: '数据总量（条）',
        value: 'dataAggr',
      }, {
        label: '数据增长情况（M）',
        value: 'dataGrw',
      }, {
        label: '存量数据年限',
        value: 'dataStock',
      }, {
        label: '数据有效期',
        value: 'dataValidity',
      }, {
        label: '是否有数据字典',
        value: 'dataDict',
      }, {
        label: '是否在用其它部门数据',
        value: 'callOtherDept',
      }, {
        label: '系统数据共享范围',
        value: 'dataShareScope',
      }, {
        label: '等级保护',
        value: 'levelProtect',
      }, {
        label: '系统开发厂商',
        value: 'sysDev',
      }, {
        label: '厂商联系人',
        value: 'vendCntct',
      }, {
        label: '厂商联系方式',
        value: 'mfrCntct',
      },{
        label: "系统维护厂商",
        value: "systemManufacturer",
      }, {
        label: "系统维护评价",
        value: "systemEvaluate",
      }, {
        label: "系统维护厂商联系人",
        value: "systemPeople",
      }, {
        label: "系统维护厂商联系方式",
        value: "systemPhone",
      },
    ],
  },
]
