import { getDic } from '@/util/dic'

export default {
  computed: {
    detailOption () {
      return {
        option: [
          {
            column: [
              {
                label: "系统所属部门",
                type: "input",
                prop: "sysDeptName",
                span: 12,
              },
              {
                label: "信息系统名称",
                type: "input",
                prop: "sysDsgt",
                span: 12,
              },
              {
                label: "系统功能、服务简介",
                type: "input",
                prop: "sysFctn",
                span: 12,
              },
              {
                label: "项目立项审批部门",
                type: "input",
                prop: "apvlDept",
                span: 12,
              },
              {
                label: "项目立项审批日期",
                type: "date",
                prop: "apvlDate",
                span: 12,
              },
              {
                label: "预算项目名称",
                prop: "bdgtDsgt",
                type: "input",
                span: 12,
              },
              {
                label: "预算涉及的年度起",
                prop: "bdgtStrt",
                type: "date",
                span: 12,
              },
              {
                label: "预算涉及的年度止",
                prop: "bdgtDeadline",
                type: "date",
                span: 12,
              },
              {
                label: "是否为僵尸系统",
                prop: "uselessSys",
                type: "select",
                dicData: getDic("IS_ZOMBIE_SYS"),
                span: 12,
              },
              {
                label: "系统开始使用日期",
                prop: "sysStart",
                span: 12,
                type: "date",
              },
              {
                label: "系统停止使用日期",
                prop: "sysExpr",
                span: 12,
                type: "date",
              },
              {
                label: "系统状态",
                prop: "sysStateList",
                type: "select",
                span: 12,
                dicData: getDic("SYSTEM_STATUS"),
              },
              {
                label: "建设资金来源",
                prop: "fundsSourcesList",
                type: "select",
                multiple: true,
                span: 12,
                dicData: getDic("SOURCE_OF_CONSTRUCTION"),
              },
              {
                label: "归口业务处室",
                prop: "servOfc",
                type: "input",
                span: 12,
              },
              {
                label: "处室联系人",
                prop: "cntct",
                type: "input",
                span: 12,
              },
              {
                label: "处室联系方式",
                prop: "cntctInfo",
                type: "input",
                span: 12,
              },
              {
                label: "系统部署情况",
                prop: "sysDeploy",
                type: "select",
                multiple: true,
                dict: getDic("SYSTEM_DEPLOYMENT"),
                span: 12,
              },
              {
                label: "网络环境",
                prop: "ntwk",
                type: "select",
                span: 12,
                dicData: getDic("NETWORK_ENVIRONMENT"),
              },
              {
                label: "使用范围-区域",
                prop: "useRange",
                type: "select",
                multiple: true,
                dicData: getDic("SCOPE_OF_USE_AREA"),
                span: 12,
              },
              {
                label: "使用范围-用户",
                prop: "useUser",
                type: "select",
                multiple: true,
                dicData: getDic("USER_SCOPE_USER"),
                span: 12,
              },
              {
                label: "系统使用频率（上年度累计访问数）",
                prop: "sysUsed",
                span: 12,
              },
              {
                label: "使用频率测算依据",
                prop: "usedBasis",
                type: "select",
                dicData: getDic("BASIS_FOR_USAGE_FREQUENCY"),
                span: 12,
              },
              {
                label: "数据产生方式",
                prop: "dataGen",
                type: "select",
                dicData: getDic("DATA_GENERATION_MODE"),
                span: 12,
              },
              {
                label: "数据更新频率",
                prop: "dataUpd",
                type: "select",
                dicData: getDic("DATA_GENERATION_MODE"),
                span: 12,
              },
              {
                label: "数据库格式",
                prop: "dbTypeList",
                type: "select",
                multiple: true,
                dict: "DATABASE_FORMAT",
                dicData: getDic("DATABASE_FORMAT"),
                span: 12,
              },
              {
                label: "数据规模（G）",
                prop: "dataSize",
                span: 12,
              },
              {
                label: "数据总量（条）",
                prop: "dataAggr",
                span: 12,
              },
              {
                label: "数据增长情况（M）",
                prop: "dataGrw",
                span: 12,
              },
              {
                label: "存量数据年限",
                prop: "dataStock",
                span: 12,
              },
              {
                label: "数据有效期",
                prop: "dataValidity",
                span: 12,
              },
              {
                label: "是否有数据字典",
                prop: "dataDict",
                type: "select",
                dict: "IS_DATA_DICT",
                dicData: getDic("IS_DATA_DICT"),
                span: 12,
              },
              {
                label: "是否在用其它部门数据",
                prop: "callOtherDept",
                type: "select",
                dict: "USING_DATA_OTHER_DEPT",
                dicData: getDic("USING_DATA_OTHER_DEPT"),
                span: 12,
              },
              {
                label: "系统数据共享范围",
                prop: "dataShareScopeList",
                type: "select",
                dict: "SYSTEM_DATA_SHARING_SCOPE",
                dicData: getDic("SYSTEM_DATA_SHARING_SCOPE"),
                span: 12,
              },
              {
                label: "等级保护",
                prop: "levelProtect",
                type: "select",
                dict: "GRADE_PROTECTION",
                dicData: getDic("GRADE_PROTECTION"),
                span: 12,
              },
              {
                label: "系统开发厂商",
                prop: "sysDev",
                span: 12,
              },
              {
                label: "厂商联系人",
                prop: "vendCntct",
                span: 12,
              },
              {
                label: "厂商联系方式",
                prop: "mfrCntct",
                span: 12,
              },
            ],
          },
        ],
      }
    },
  },
}